#!/usr/bin/env bash
PYTHON=python
if [[ -z ${_SMOLT_CLIENT_BASE} ]]; then
    _SITE_PACKAGES=$(${PYTHON} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")
    _SMOLT_CLIENT_BASE=${_SITE_PACKAGES}/smolt/client
fi

PYTHONPATH=${_SMOLT_CLIENT_BASE} \
        ${PYTHON} ${_SMOLT_CLIENT_BASE}/sendProfile.py $*
