.TH SMOLTDELETEPROFILE 1 "February 27 2008"
.SH NAME
smoltDeleteProfie \- Delete Smolt hardware profile from server
.SH SYNOPSIS
.B smoltDeleteProfile
.RI [options]
.SH DESCRIPTION
\fBsmoltDeleteProfile\fP deletes the machine's profile from a remote Smoon
server. Smolt is a cross-desktop hardware reporting tool for GNU/Linux based
systems.
.TP
.SH OPTIONS
.TP
\-s \fISMOON_URL\fR, \-\-server=\fISMOON_URL\fR
Specify the URL of the server
.TP
\-u \fIUSERAGENT\fR, \-\-useragent=\fIUSERAGENT\fR, \-\-user_agent=\fIUSERAGENT\fR
Specify HTTP user agent (default "smolt/0.97")
.TP
\-t \fITIMEOUT\fR, \-\-timeout=\fITIMEOUT\fR
Specify HTTP timeout in seconds (default 60.0 seconds)
.TP
\-\-uuidFile=\fIUUIDFILE\fR
Specify which UUID to use; useful for debugging and testing
.TP
\-d, \-\-debug
Enable debug information
.TP
\-\-version
Show program's version number and exit
.TP
\-h, \-\-help
Show this help message and exit
.SH SEE ALSO
.BR smoltSendProfile (1),
.BR smoltGui (1).
.SH AUTHOR
\fBsmoltSendProfile\fP was written by Mike McGrath <mmcgrath@redhat.com> and others.
.PP
This manual page was written by Chris Lamb <chris@chris-lamb.co.uk>,
for the Debian project (but may be used by others).
