.TH SMOLTGUI 1 "February 27 2008"
.SH NAME
smoltGui \- GUI for Smolt hardware profile submission
.SH SYNOPSIS
.B smoltGui
.SH DESCRIPTION
\fBsmoltGui\fP is a graphical user interface that can be used to submit Smolt
hardware profiles to a Smoon server. Smolt is a cross-desktop hardware reporting
tool for GNU/Linux based systems.
.SH OPTIONS
.TP
\fBsmoltGui\fP has no command-line options.
.SH SEE ALSO
.BR smoltSendProfile (1),
.BR smoltDeleteProfile (1).
.SH AUTHOR
\fBsmoltGui\fP was written by Mike McGrath <mmcgrath@redhat.com> and others.
.PP
This manual page was written by Chris Lamb <chris@chris-lamb.co.uk>,
for the Debian project (but may be used by others).
