#!/usr/bin/env bash
PYTHON=python
if [[ -z ${_SMOLT_SERVER_BASE} ]]; then
    _SITE_PACKAGES=$(${PYTHON} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")
    _SMOLT_SERVER_BASE=${_SITE_PACKAGES}/smolt/server
fi

(
    echo cd \""${_SMOLT_SERVER_BASE}"\"
    cd "${_SMOLT_SERVER_BASE}" || {
        echo "Could not cd into '${_SMOLT_SERVER_BASE}'"
        exit 1
    }
    ${PYTHON} database-admin.py $*
)
